common:
  output_directory: outputs
  default_n_jobs: 1
steps:
  - type: filter
    parameters:
      inputs:
        - ../dataset/WikiMatrix.en-ru.en
        - ../dataset/WikiMatrix.en-ru.ru
      outputs:
        - dataset/FilteredWikiMatrix.en-ru.en
        - dataset/FilteredWikiMatrix.en-ru.ru
      filters:
        - LanguageIDFilter:
            id_method: langid
            languages: [ en, ru ]
            thresholds: [ 1, 1 ]
        - LengthFilter:
            min_length: 3
            max_length: 100
            unit: word
        - AlphabetRatioFilter:
            threshold: 0.75
        - HtmlTagFilter: {}


