common:
  output_directory: outputs
steps:
  - type: preprocess
    parameters:
      inputs:
        - ../dataset/WikiMatrix.en-ru.en
        - ../dataset/WikiMatrix.en-ru.ru
      outputs:
        - preprocessed_WikiMatrix.en-ru.en
        - preprocessed_WikiMatrix.en-ru.ru
      preprocessors:
        - RegExpSub:
            patterns:
              - [ '"', '', 0, '' ]
              - [ ' / ', ' ', 0, '' ]
              - [ '»', '', 0, '' ]
              - [ '«', '', 0, '' ]
  - type: filter
    parameters:
      inputs:
        - preprocessed_WikiMatrix.en-ru.en
        - preprocessed_WikiMatrix.en-ru.ru
      outputs:
        - FilteredWikiMatrix.en-ru.en
        - FilteredWikiMatrix.en-ru.ru
      filters:
        - LanguageIDFilter:
            id_method: cld2
            languages: [ en, ru ]
            thresholds: [ 0.9, 0.9 ]
        - LengthFilter:
            min_length: [ 3, 4 ]
            max_length: 100
            unit: word
        - AlphabetRatioFilter:
            threshold: 0.75
            exclude_whitespace: true
        - RegExpFilter:
            regexps: '\{\\'


