common:
  output_directory: outputs
steps:
  - type: filter
    parameters:
      inputs:
        - ../dataset/WikiMatrix.en-ru.en
        - ../dataset/WikiMatrix.en-ru.ru
      outputs:
        - FilteredWikiMatrix.en-ru.en
        - FilteredWikiMatrix.en-ru.ru
      filters:
        - LanguageIDFilter:
            id_method: cld2
            languages: [ en, ru ]
            thresholds: [ 0.9, 0.9 ]
        - LengthFilter:
            min_length: [ 3, 4 ]
            max_length: 100
            unit: word
        - AlphabetRatioFilter:
            threshold: 0.75
            exclude_whitespace: true


